name:          Code Guide for Situation Interactive
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           http://blind3y3design.github.io/sitch.co-code_guide/

markdown:      rdiscount
permalink:     pretty
pygments:      true
